name: GitHub Actions
on: [push]
jobs: 
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps: 
      - run: build
      - run: lint:js
      - run: lint:css
      - run: analyze
      - run: validate
